#!/usr/bin/env python

import charlie
import datetime as dt

for train in charlie.train_list:
    train = charlie.train_list[train]
    curStop = train.getNextEvent()
    if not curStop:
        continue

    preStop = train.getStop( curStop["prev"] )
    if not preStop:
        continue

    curStation = charlie.get_station_by_stop( curStop["PlatformKey"] )
    preStation = charlie.get_station_by_stop( preStop["PlatformKey"] )

    payload = {
        "root" : {
            "id" : curStation.name
        },
        "dest" : {
            "id" : preStation.name    
        }
    }
    print payload
