#!/usr/bin/env python

import charlie

for train in charlie.train_list:
    train = charlie.train_list[train]
    curStop = train.getNextEvent()
    if not curStop:
        continue

    preStop = train.getStop( curStop["prev"] )
    if not preStop:
        continue

    print ( curStop["TargetTime"] - preStop["TargetTime"] )
