#!/usr/bin/env python

import charlie

for line in charlie.line_list:
    print line
    for station in charlie.line_list[line].getStations():
        print "  " + station
        for platform in charlie.station_list[station].getPlatforms():
            print "    " + platform
